"""Delete and recreate the profile repo, then restore everything.

WHY THIS EXISTS. github.com/Ujjwalkumar-pm will not display the profile README,
and every documented precondition is verified: repo name == owner == login
byte-for-byte, User account, public, not a fork, default branch main, README.md
at root, renders correctly on the repo page and through GitHub's /markdown API.
A touch-commit, a private->public toggle, and a rename-away-and-back all had no
effect over ~2 hours.

The remaining difference between this repo and one that works is how it was
created. `gh repo create --source` makes an EMPTY repo and pushes into it;
GitHub's special-repo detection is reliable for repos created WITH an initial
commit (`auto_init`, i.e. the "Add a README file" tick on github.com/new). The
repo ID also changes, which matters if the negative result is cached against it.

Nothing is lost: full history is local, and the snake SVGs on the `output`
branch are regenerated by the workflow in about a minute.

    gh auth refresh -s delete_repo      # one-time, opens a browser
    .venv/bin/python recreate.py
"""

import json
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent
USER = "Ujjwalkumar-pm"
REPO = f"{USER}/{USER}"
DESC = "Profile README — animated terminal banner, generated from source in banner/"


def sh(*args, check=True, **kw):
    return subprocess.run(args, capture_output=True, text=True, check=check,
                          cwd=ROOT, **kw)


def gh(*args, check=True):
    return sh("gh", *args, check=check).stdout.strip()


def step(msg):
    print(f"\n>> {msg}")


def profile_shows_readme():
    req = urllib.request.Request(f"https://github.com/{USER}?v={time.time()}",
                                 headers={"User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = r.read().decode(errors="ignore")
    except Exception:                                          # noqa: BLE001
        return False
    return any(k in body for k in ("dark.svg", "streak-stats", "VISUAL"))


def main():
    # ---- guards: never destroy anything that is not fully recoverable ------
    step("Pre-flight")
    if sh("git", "status", "--porcelain").stdout.strip():
        sys.exit("working tree is dirty — commit or stash first")
    head = sh("git", "rev-parse", "HEAD").stdout.strip()
    ahead = sh("git", "rev-list", "--count", "origin/main..HEAD").stdout.strip()
    if ahead != "0":
        sys.exit(f"{ahead} local commits are not on origin — push first")
    n = sh("git", "rev-list", "--count", "HEAD").stdout.strip()
    print(f"   local HEAD {head[:8]}, {n} commits, tree clean")

    if "delete_repo" not in gh("auth", "status"):
        sys.exit("token lacks delete_repo. Run:  gh auth refresh -s delete_repo")

    # ---- delete -----------------------------------------------------------
    step(f"Deleting {REPO}")
    gh("repo", "delete", REPO, "--yes")
    time.sleep(8)

    # ---- recreate WITH an initial commit ----------------------------------
    step("Recreating with auto_init (the github.com/new path)")
    gh("api", "-X", "POST", "/user/repos",
       "-f", f"name={USER}", "-f", f"description={DESC}",
       "-F", "private=false", "-F", "auto_init=true", "--silent")
    time.sleep(10)
    info = json.loads(gh("api", f"repos/{REPO}"))
    print(f"   created id={info['id']} default={info['default_branch']}")

    # ---- restore ----------------------------------------------------------
    step("Force-pushing the real history over the placeholder commit")
    sh("git", "push", "--force", "origin", "main")
    time.sleep(5)

    step("Re-enabling Actions write permission")
    gh("api", "-X", "PUT", f"repos/{REPO}/actions/permissions/workflow",
       "-f", "default_workflow_permissions=write",
       "-F", "can_approve_pull_request_reviews=false", "--silent")

    step("Regenerating the snake (rebuilds the output branch)")
    time.sleep(5)
    gh("workflow", "run", "Generate Snake Animation", "--repo", REPO, check=False)
    for _ in range(20):
        time.sleep(20)
        out = gh("run", "list", "--repo", REPO, "--limit", "1",
                 "--json", "status,conclusion",
                 "--jq", '.[0] | "\\(.status) \\(.conclusion // "-")"', check=False)
        print(f"   {out}")
        if "completed" in out:
            break

    # ---- verify -----------------------------------------------------------
    step("Verifying")
    branches = gh("api", f"repos/{REPO}/branches", "--jq", '[.[].name]|join(",")')
    print(f"   branches: {branches}")
    for path in ("main/dark.svg", "main/light.svg",
                 "output/github-snake-dark.svg"):
        url = f"https://raw.githubusercontent.com/{USER}/{USER}/{path}"
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                print(f"   {path}: HTTP {r.status} {len(r.read())//1024} KB")
        except Exception as exc:                               # noqa: BLE001
            print(f"   {path}: FAILED {exc}")

    step("Waiting for the profile page to pick up the README")
    for i in range(1, 13):
        if profile_shows_readme():
            print(f"   [{i}] APPEARED — github.com/{USER} is live")
            return 0
        print(f"   [{i}] not yet")
        time.sleep(30)
    print("   still not showing; the repo itself is correct and complete")
    return 1


if __name__ == "__main__":
    sys.exit(main())
